baseurl = "https://www.rushtehrani.com/"
languageCode = "en-us"
title = "Rush Tehrani"
theme = "simple"

enableRobotsTXT = true

[params]
    highlight = "github"

[author]
    email = "hello@rushtehrani.com"
    name = "Rush Tehrani"
    github = "rushtehrani"
    linkedin = "rushtehrani"
    facebook = "rustehrani"
    google = "RushTehrani"
    gaID = "UA-54533300-1"
    twitter = "rushtehrani"

[blackfriday]
  hrefTargetBlank = true
