baseurl = "http://www.rushtehrani.com.s3-website-us-west-2.amazonaws.com/"
languageCode = "en-us"
title="Rush Tehrani"
theme="simple"

[params]
    highlight="github"

[author]
    email = "hello@rushtehrani.com"
    name = "Rush Tehrani"
    github = "rushtehrani"
    linkedin = "rushtehrani"
    facebook = "rustehrani"
    google = "RushTehrani"
    gaID = "UA-54533300-1"
    twitter = "rushtehrani"
